CREATE TABLE pagamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    valor decimal NOT NULL,
    nome varchar DEFAULT NULL,
    numero varchar DEFAULT NULL,
    expiracao varchar NOT NULL,
    codigo varchar DEFAULT NULL,
    status varchar NOT NULL,
    forma_de_pagamento_id bigint NOT NULL,
    pedido_id bigint NOT NULL,
    PRIMARY KEY (id)
  );
