spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:distancia
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false