CREATE TABLE restaurante (
                             id bigint GENERATED BY DEFAULT AS IDENTITY,
                             cep varchar NOT NULL,
                             tipo_de_cozinha_id bigint NOT NULL
) ;
